# Generated by Django 3.2 on 2023-03-28 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название товара', max_length=100, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(help_text='Укажите цену на товар', null=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, help_text='Введите описание товара', max_length=1000, verbose_name='Описание товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Выберите время создания объявления', verbose_name='Время создания объявления')),
                ('image', models.ImageField(blank=True, help_text='Разместите фото для объявления', null=True, upload_to='images/', verbose_name='Фото')),
                ('author', models.ForeignKey(help_text='Введите автора объявления', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Оставьте свой комментарий', max_length=1000, null=True, verbose_name='текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Выберите время создания комментария', null=True, verbose_name='Время создания комментария')),
                ('ad', models.ForeignKey(help_text='Объявление, к которому относится комментарий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ads.ad', verbose_name='Объявление')),
                ('author', models.ForeignKey(help_text='Введите автора комментария', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created_at',),
            },
        ),
    ]
